### ISSUE TITLE
Feature request: Export to excel || csv

### ISSUE THREAD

**Issue by johandavidsen** [burningice2866/CompositeC1Contrib.FormBuilder#3]
It would be very nice if it was possible to export form data to Excel and CSV.

There are numerous use-cases where this would be applicable.

**Comment by burningice2866** [comment]
You can already do this; add a Save-handler to the submit handlers of your dynamic form, right click the handler and choose download. This will download the submitted forms as csv.

**Comment by johandavidsen** [comment]
Cool :) Thanks.
